### ISSUE TITLE
Add SSRN social network

### ISSUE THREAD

**Issue by TheColorDarkBlue** [rendercv/rendercv#91]
https://www.ssrn.com/

**Comment by sinaatalay** [comment]
Unfortunately, the [fontawesome5](https://ctan.org/pkg/fontawesome5?lang=en) package doesn't have the SSRN icon.

**Comment by TheColorDarkBlue** [comment]
@sinaatalay Why does it matter if their icons are not in the fontawesome package? Icons inherently should not be on resumes IMO.

**Comment by sinaatalay** [comment]
Because all of the built-in themes can use icons in the header and we wouldn’t want to remove the available functionality to add a social network without an icon.

Do you have any suggestions on what to put there in terms of design when an icon does not exist?

**Comment by TheColorDarkBlue** [comment]
> Because all of the built-in themes can use icons in the header and we wouldn’t want to remove the available functionality to add a social network without an icon.
> 
> Do you have any suggestions on what to put there in terms of design when an icon does not exist?

Nothing. Leave it empty. Icons in general may cause parsing issues in an applicant tracking system (ATS).
